"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate, useLocation } from "react-router-dom";
import { Database, Home, LayoutDashboard, LogOut, ChevronLeft, Menu } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
export default function Sidebar({ resources, open, onToggle, isSpooky = false }) {
    const navigate = useNavigate();
    const location = useLocation();
    const currentResource = location.pathname.split("/")[2];
    if (!open) {
        return (_jsxs("aside", { className: `fixed left-0 top-0 h-full w-16 ${isSpooky ? 'bg-slate-900 border-cyan-500/30' : 'bg-white border-gray-200'} border-r flex flex-col items-center py-4 z-40 shadow-sm`, children: [_jsx("button", { onClick: onToggle, className: "p-3 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 text-white hover:from-indigo-600 hover:to-purple-700 transition-all shadow-md hover:shadow-lg", title: "Expand sidebar", children: _jsx(Menu, { className: "w-5 h-5" }) }), _jsxs("nav", { className: "flex-1 flex flex-col items-center gap-2 mt-6", children: [_jsx("button", { onClick: () => navigate("/portal"), className: cn("p-3 rounded-xl transition", !currentResource ? "bg-indigo-50 text-indigo-700" : "text-gray-400 hover:bg-gray-50 hover:text-gray-600"), title: "Dashboard", children: _jsx(Home, { className: "w-5 h-5" }) }), _jsx("div", { className: "w-8 h-px bg-gray-200 my-2" }), resources.map((resource) => (_jsx("button", { onClick: () => navigate(`/portal/${resource.name}`), className: cn("p-3 rounded-xl transition", currentResource === resource.name
                                ? "bg-indigo-50 text-indigo-700"
                                : "text-gray-400 hover:bg-gray-50 hover:text-gray-600"), title: resource.displayName, children: _jsx(Database, { className: "w-5 h-5" }) }, resource.name)))] }), _jsx("button", { onClick: () => navigate("/"), className: `p-3 rounded-xl transition ${isSpooky ? 'text-cyan-400 hover:bg-slate-800 hover:text-cyan-300' : 'text-gray-400 hover:bg-gray-50 hover:text-gray-600'}`, title: "Back to Analyzer", children: _jsx(LogOut, { className: "w-5 h-5" }) })] }));
    }
    return (_jsxs("aside", { className: `fixed left-0 top-0 h-full w-64 ${isSpooky ? 'bg-slate-900 border-cyan-500/30' : 'bg-white border-gray-200'} border-r flex flex-col z-40 shadow-sm`, children: [_jsx("div", { className: `p-4 ${isSpooky ? 'border-cyan-500/20' : 'border-gray-100'} border-b`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `p-2 rounded-xl ${isSpooky ? 'bg-gradient-to-br from-cyan-600 to-teal-500' : 'bg-gradient-to-br from-indigo-500 to-purple-600'}`, children: _jsx(LayoutDashboard, { className: "w-5 h-5 text-white" }) }), _jsxs("div", { children: [_jsxs("span", { className: `font-bold ${isSpooky ? 'text-cyan-400' : 'text-gray-900'}`, children: [isSpooky ? '💀 ' : '', "Legacy Portal"] }), _jsx("p", { className: `text-xs ${isSpooky ? 'text-gray-500' : 'text-gray-500'}`, children: "API Management" })] })] }), _jsx("button", { onClick: onToggle, className: `p-2 rounded-lg transition ${isSpooky ? 'hover:bg-slate-800 text-gray-400 hover:text-cyan-400' : 'hover:bg-gray-100 text-gray-400 hover:text-gray-700'}`, title: "Collapse sidebar", children: _jsx(ChevronLeft, { className: "w-5 h-5" }) })] }) }), _jsxs("nav", { className: "flex-1 p-4 space-y-1 overflow-y-auto", children: [_jsxs("button", { onClick: () => navigate("/portal"), className: cn("w-full flex items-center gap-3 px-4 py-3 rounded-xl transition text-left", !currentResource
                            ? isSpooky ? "bg-cyan-500/20 text-cyan-400 font-medium border border-cyan-500/30" : "bg-indigo-50 text-indigo-700 font-medium"
                            : isSpooky ? "text-gray-400 hover:bg-slate-800" : "text-gray-600 hover:bg-gray-50"), children: [_jsx(Home, { className: "w-5 h-5" }), _jsx("span", { children: "Dashboard" })] }), _jsx("div", { className: "pt-6 pb-2 px-2", children: _jsx("span", { className: `text-xs font-semibold uppercase tracking-wider ${isSpooky ? 'text-gray-500' : 'text-gray-400'}`, children: "Resources" }) }), resources.map((resource) => (_jsxs("button", { onClick: () => navigate(`/portal/${resource.name}`), className: cn("w-full flex items-center gap-3 px-4 py-3 rounded-xl transition text-left", currentResource === resource.name
                            ? isSpooky ? "bg-cyan-500/20 text-cyan-400 font-medium border border-cyan-500/30" : "bg-indigo-50 text-indigo-700 font-medium"
                            : isSpooky ? "text-gray-400 hover:bg-slate-800" : "text-gray-600 hover:bg-gray-50"), children: [_jsx(Database, { className: "w-5 h-5" }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { children: resource.displayName }), _jsxs("div", { className: `text-xs ${isSpooky ? 'text-gray-500' : 'text-gray-400'}`, children: [resource.fields.length, " fields"] })] })] }, resource.name)))] }), _jsxs("div", { className: `p-4 ${isSpooky ? 'border-cyan-500/20' : 'border-gray-100'} border-t`, children: [_jsxs("div", { className: `text-xs mb-3 ${isSpooky ? 'text-gray-500' : 'text-gray-400'}`, children: [resources.length, " resource", resources.length !== 1 ? "s" : "", " loaded"] }), _jsxs(Button, { variant: "outline", size: "sm", onClick: () => navigate("/"), className: `w-full justify-start rounded-xl ${isSpooky ? 'border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/10 hover:text-cyan-300' : 'text-gray-600 hover:text-gray-900 border-gray-200 hover:bg-gray-50'}`, children: [_jsx(LogOut, { className: "w-4 h-4 mr-2" }), "Back to Analyzer"] })] })] }));
}
