/**
 * Base project file templates (README, CSS, utils)
 */

export const readmeTemplate = `# Admin Portal

Auto-generated admin portal for your legacy API.

## 🚀 Quick Start

### Prerequisites
- Node.js 18+
- npm or yarn

### Installation

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev
\`\`\`

The app will be available at \`http://localhost:5173\`

### Build for Production

\`\`\`bash
npm run build
\`\`\`

The production build will be in the \`dist/\` directory.

## 🔧 Configuration

### API Base URL

Edit \`.env\` file to configure your API endpoint:

\`\`\`
API_BASE_URL=https://your-api.com
\`\`\`

### Resources

Resource schemas are defined in \`src/config/resources.ts\`. You can modify field types, display names, and available operations there.

## 📁 Project Structure

\`\`\`
src/
├── components/       # React components
│   ├── ui/          # UI primitives (buttons, inputs, etc.)
│   ├── Dashboard.tsx
│   ├── Sidebar.tsx
│   ├── ResourceList.tsx
│   ├── ResourceDetail.tsx
│   └── ResourceForm.tsx
├── services/        # API service layer
│   └── api.ts
├── config/          # Configuration
│   └── resources.ts
├── types/           # TypeScript types
│   └── index.ts
├── lib/             # Utilities
│   └── utils.ts
├── App.tsx          # Main app component
└── main.tsx         # Entry point
\`\`\`

## 🎨 Customization

### Styling

This project uses Tailwind CSS. Customize styles in:
- \`tailwind.config.js\` - Tailwind configuration
- \`src/index.css\` - Global styles
- Component files - Component-specific styles

### Adding Features

1. **Add new routes**: Edit \`src/App.tsx\`
2. **Add new components**: Create in \`src/components/\`
3. **Modify API calls**: Edit \`src/services/api.ts\`

## 📝 License

MIT License - feel free to use and modify as needed.

---

Generated by Legacy UX Reviver
`;

export const indexCssTemplate = `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 222.2 84% 4.9%;
    --radius: 0.5rem;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}`;

export const utilsTemplate = `import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}`;

export const typesTemplate = `/**
 * Core TypeScript types for the admin portal
 */

export interface ResourceField {
  name: string
  type: string
  displayName: string
}

export interface ResourceSchema {
  name: string
  displayName: string
  endpoint: string
  primaryKey: string
  fields: ResourceField[]
  operations: string[]
}`;
